- hosts: desktops:&arch
  tasks:
  - import_tasks: aur.yaml
    vars: {"pkg": "duc", "keys": ["CACDA4B54202FA2F"]}
  - import_tasks: aur.yaml
    vars: {"pkg": "grb-git"}
  - import_tasks: aur.yaml
    vars: {"pkg": "kjv-apocrypha"}
  - import_tasks: aur.yaml
    vars: {"pkg": "libcgroup", "keys": ["47A68FCE37C7D7024FD65E11356CE62C2B524099"]}
  - import_tasks: aur.yaml
    vars: {"pkg": "mit-scheme", "keys": ["C9E40BAAFD0CB132"]}
  - import_tasks: aur.yaml
    vars: {"pkg": "opencl-1.2-man-doc"}
  - import_tasks: aur.yaml
    vars: {"pkg": "otf-gfs"}
  - import_tasks: aur.yaml
    vars: {"pkg": "pam-gnupg"}
  - import_tasks: aur.yaml
    vars: {"pkg": "renderdoc", "keys": ["AC612C3120C34695"]}
  - import_tasks: aur.yaml
    vars: {"pkg": "stellarium", "keys": ["9380E47C0374E169"]}
  - import_tasks: aur.yaml
    vars: {"pkg": "task-spooler"}
  - import_tasks: aur.yaml
    vars: {"pkg": "ttf-aquiline-two"}
  - import_tasks: aur.yaml
    vars: {"pkg": "ttf-marcellus"}
  - import_tasks: aur.yaml
    vars: {"pkg": "ttf-sbl-greek"}
  - import_tasks: aur.yaml
    vars: {"pkg": "urxvt-resize-font-git"}
  - import_tasks: aur.yaml
    vars: {"pkg": "vim-diffchar"}
  - import_tasks: aur.yaml
    vars: {"pkg": "vim-dispatch", "keys": ["E09E474A404A3A45"]}
  - import_tasks: aur.yaml
    vars: {"pkg": "vim-vimtex"}
  - import_tasks: aur.yaml
    vars: {"pkg": "vul-git"}
