- hosts: all
  tags: base
  vars:
    home: '{{ ansible_env.HOME }}'
    src_dir: '{{ home }}/src'
  tasks:
  - name: create source directory
    file:
      state: directory
      path: '{{ src_dir }}'
  - name: clone dotfiles repository
    git:
      repo: https://bbguimaraes@github.com/bbguimaraes/dotfiles.git
      dest: '{{ src_dir }}/dotfiles'
      update: no
  - name: create home directories
    file:
      state: directory
      path: '{{ home }}/{{ item }}'
    loop:
    - .config/git
    - .vim/colors
  - name: setup dotfile symlinks
    file:
      state: link
      src: '{{ src_dir }}/dotfiles/{{ item.0 }}'
      dest: '{{ home }}/{{ item.1 }}'
    loop:
    - ['bash/profile',         '.bash_profile']
    - ['bash/bashrc',          '.bashrc']
    - ['git/config',           '.config/git/config']
    - ['bash/inputrc',         '.inputrc']
    - ['tmux.conf',            '.tmux.conf']
    - ['vim/preto.vim',        '.vim/colors/preto.vim']
    - ['vim/vimrc',            '.vimrc']
